# Site settings
title: Client Name
email: dev@ocupop.com
description: ''
url: "http://client_url.com"
permalink: pretty
analytics_code:

# Collections
collections:
  examples:
    output: true
    layout: default
    permalink: /examples/:path/

# defaults:
#   - 
#     scope:
#       type: 'examples'
#     values:
#       layout: default
#       variable_name: value

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-lunr-js-search


# feed:
#   title: Client Name
#   description: Description of feed
#   url: primary url
#   path: alternate path