# Site settings
title: Client Name
email: dev@ocupop.com
url: "http://client_url.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: assets/img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics_code:


# Collections
collections:
  directors:
    output: true
    layout: director
    permalink: /directors/:path/

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-lunr-js-search


# feed:
#   title: Client Name
#   description: Description of feed
#   url: primary url
#   path: alternate path

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder