# Site settings
title: Client Name
email: dev@ocupop.com
url: "https://velocityclinical.com/"
permalink: pretty

# Social sharing
description: 'Velocity Clinical Research is 100% committed to the successful delivery of clinical studies—helping our clients maintain the highest standards of care while bringing new medications directly to the patients who need them, as quickly and efficiently as possible.'
socialshare:
  featured_image: assets/img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics_code: UA-106357720-7



# Collections
collections:
  team:
    output: true
    layout: team
    permalink: /team/:path/

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-lunr-js-search


# feed:
#   title: Client Name
#   description: Description of feed
#   url: primary url
#   path: alternate path

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder

_options:
  layout:
    hidden: true

_comments:
  layout: 
  name: 'Full name, including designations'
  role: 'Displays in email signature if present'
  phone: 'Displays in email signature if present'
