# Site settings
title: Client Name
email: dev@ocupop.com
url: "https://velocityclinical.com/"
permalink: pretty

# Social sharing
description: 'Velocity Clinical Research is 100% committed to the successful delivery of clinical studies—helping our clients maintain the highest standards of care while bringing new medications directly to the patients who need them, as quickly and efficiently as possible.'
socialshare:
  featured_image: /img/socialshare.png
  twitter:
    username:
    image: /img/socialshare.png

# Google Analytics
analytics_code: UA-140308205-1



# Collections
collections:
  team:
    output: false
  locations:
    output: false
  specialties:
    output: true
  posts:
    output: true
    permalink: /posts/:title/  

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: 'https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder'
placeholder_image_wide: 'https://via.placeholder.com/1900x800/333333/000000?text=Placeholder'

_options:
  layout:
    hidden: true

_array_structures:
  meta:
    label: Meta Data
    icon: share
    value:
      title:
      description:
      image:
  hero: 
    - label: Hero
      icon: panorama
      value:
        image:
        title:
        subtitle:
        color_overlay: false
  statistic:
    - label: Statistic
      icon: insert_chart_outlined
      value:
        number:
        description:
  list_section:
    - label: List Section
      icon: format_list_bulleted
      value:
        title:
        list_item:
  capability:
    - label: Capability
      icon: view_list
      value:
        title:
        list_item:
  list_item:
    - label: List item        
      icon: view_list
      value:
        title:
  text_carousel:
    - label: Text Carousel
      icon: view_carousel
      value:
        text_slide:
  text_slide:
    - label: Text Slide
      icon: text_snippet
      value:
        title:
        subtitle:
        link:
        link_label:
  location_team:
    label: Location Team
    icon: face
    value:
      name:
      role:
      image:
      bio_html:


_comments:
  layout: 
  name: 'Full name, including designations'
  role: 'Displays in email signature if present'
  phone: 'Displays in email signature if present'
