# Site settings
title: Client Name
email: dev@ocupop.com
url: "https://velocityclinical.com/"
permalink: pretty

# Social sharing
description: 'Velocity Clinical Research is 100% committed to the successful delivery of clinical studies—helping our clients maintain the highest standards of care while bringing new medications directly to the patients who need them, as quickly and efficiently as possible.'
socialshare:
  featured_image: /img/socialshare.png
  twitter:
    username:
    image: /img/socialshare.png

# Google Analytics
analytics_code: UA-140308205-1



# Collections
collections:
  team:
    output: true
    layout: team
    permalink: /team/:path/
  locations:
    output: false
  specialties:
    output: true    

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: 'https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder'
placeholder_image_wide: 'https://via.placeholder.com/1900x800/333333/000000?text=Placeholder'

_options:
  layout:
    hidden: true

_array_structures:
  hero: 
    - label: Hero
      icon: panorama
      value:
        _type: hero
        image:
        title:
        subtitle:
        color_overlay: false
  statistic:
    - label: Statistic
      icon: insert_chart_outlined
      value:
        number:
        description:
  list_section:
    - label: List Section
      icon: format_list_bulleted
      value:
        title:
        list_items:
  capabilities:
    - label: Capabilities
      icon: view_list
      value:
        title:
        list_items:
  list_item:
    - label: List item        
      icon: view_list
      value:
        title:


_comments:
  layout: 
  name: 'Full name, including designations'
  role: 'Displays in email signature if present'
  phone: 'Displays in email signature if present'
