name: Location Manager
on:
  push:
    branches: ['develop']
    paths: ['src/_locations/**']

jobs:
  sync_locations:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 setup
        uses: actions/checkout@v2
      - name: filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          # Use context to get branch where commits were pushed.
          # If there is only one long lived branch (e.g. master),
          # you can specify it directly.
          # If it's not configured, the repository default branch is used.
          list-files: json
          base: ${{ github.ref }}
          filters: |
            locations:
              - added|deleted: 'src/_locations/**'

      # run only if 'location' files were added or deleted
      - name: copy
        if: steps.filter.outputs.locations == 'true'
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /src/locations/_default/.
          dst_path: /src/locations/test/
          dst_owner: VelocityClinical
          dst_repo_name: velocity-clinical-research
          commit_message: added location files

